# Generated by Django 2.2.5 on 2019-10-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrialBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.CharField(max_length=30)),
                ('accountAssetType', models.CharField(max_length=30)),
                ('accountSubType', models.CharField(max_length=30)),
                ('accountClass', models.CharField(max_length=30)),
                ('accountSubClass', models.CharField(max_length=30)),
                ('beginningBalance', models.IntegerField(max_length=30)),
                ('endingBalance', models.IntegerField(max_length=30)),
            ],
        ),
    ]
