# Generated by Django 2.2.5 on 2019-10-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialBalanceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='trialbalance',
            name='beginningBalance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trialbalance',
            name='endingBalance',
            field=models.IntegerField(),
        ),
    ]
