# Generated by Django 2.2.5 on 2019-10-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20191008_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trialbalancefile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='trialbalancefile',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='trialbalancefile',
            name='document',
            field=models.FileField(upload_to=''),
        ),
    ]
