# Generated by Django 2.2.5 on 2019-10-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_auto_20191009_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialbalancefile',
            name='document',
            field=models.FileField(upload_to=''),
        ),
    ]
