# Generated by Django 2.2.5 on 2019-10-09 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_auto_20191009_1048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrialBalance',
        ),
    ]
