# Generated by Django 2.2.5 on 2019-10-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_delete_trialbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.CharField(max_length=30)),
                ('account', models.CharField(max_length=30)),
                ('AssetType', models.CharField(max_length=30)),
                ('accountSubType', models.CharField(max_length=30)),
                ('accountClass', models.CharField(max_length=30)),
                ('accountSubClass', models.CharField(max_length=30)),
                ('beginningBalance', models.FloatField()),
                ('endingBalance', models.FloatField()),
            ],
        ),
    ]
